DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Stores;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
	Id INT IDENTITY,
	[Name] VARCHAR(100) NOT NULL,
	[Address] VARCHAR(100) NOT NULL,
	CONSTRAINT [PK_Customer] PRIMARY KEY (Id)
)

CREATE TABLE Products (
	Id INT IDENTITY,
	[Name] VARCHAR(100) NOT NULL,
	Price DECIMAL (10,2) NOT NULL,
	CONSTRAINT [PK_Products] PRIMARY KEY (Id)
)

CREATE TABLE Stores (
	Id INT IDENTITY,
	[Name] VARCHAR(100) NOT NULL,
	[Address] VARCHAR(100) NOT NULL,
	CONSTRAINT [PK_Stores] PRIMARY KEY (Id)
)

CREATE TABLE Sales (
	Id INT IDENTITY,
	ProductId INT NOT NULL,
	CustomerId INT NOT NULL,
	StoreId INT NOT NULL,
	DateSold DATETIME2 NOT NULL,
	CONSTRAINT [PK_Sales] PRIMARY KEY (Id),
	CONSTRAINT [FK_Sales_Product] 
		FOREIGN KEY (ProductId) REFERENCES Products (Id),
	CONSTRAINT [FK_Sales_Customers] 
		FOREIGN KEY (CustomerId) REFERENCES Customers (Id),
	CONSTRAINT [FK_Sales_Stores] 
		FOREIGN KEY (StoreId) REFERENCES Stores (Id)
)
